services:
  docs:
    image: radasafi_local_docs
    container_name: radasafi_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.env.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./radasafi:/app/radasafi:z
    ports:
      - '9000:9000'
    command: /start-docs
