# Generated by Django 5.0.6 on 2024-06-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='general_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='from_latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='from_longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='to_latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='to_longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='end_location',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_end_location', to='events.location', verbose_name='event_end_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_location',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_start_location', to='events.location', verbose_name='event_start_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(to='events.category'),
        ),
    ]
